; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200

lib_deps = 
    olikraus/U8g2@^2.36.0
<<<<<<< HEAD
<<<<<<< HEAD
	paulstoffregen/OneWire@^2.3.5
	milesburton/DallasTemperature@^3.9.0
	
=======
	paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
>>>>>>> 42d634d (Temperature sensing working for device is working now.)
=======
	paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
>>>>>>> 42d634d83717d1e0e906d1f00abfdc7a64fc3a7d
